name: Publish And Deploy Demo
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: unbuntu-lasest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master

    # 打包构建
    - name: Build
      uses: actions/setup-node@master
      run: npm install
      run: npm run build
      run: tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json

    # 发布 Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN:${{ secrets.TOKEN }}
      with: 
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    # 上传构建结果到Release
    - name: Upload Release Asset
      id: uplaod-release-asset
      uses:  actions/uplaod-release-asset@master
      env: 
        GITHUB_TOKEN: ${{ screts.TOKEN }}
      upload_url: ${{ steps.creare_release.outputs.upload_url }}
      asset_path: ./release.tgz
      asset_name: release.tgz
      asset_content_type: application/x-tgz
    
    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/realworld-nuxtjs
          wget https://github.com/songyi/realworldnuxtjs/releases/latest/download/release.tgz 
          -O release.tgz
          tar zxvf release.tgz
          npm install --production
          pm2 reload pm2.config.js
